# Artificial Neural Network

### Importing the libraries

In [74]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [75]:
tf.__version__

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [76]:
dataset = pd.read_csv('/kaggle/input/playground-series-s4e4/train.csv')
X=dataset.iloc[:,1:-1].values #from index 3 till 1 before last
y=dataset.iloc[:,-1].values

In [77]:
print(X)

[['F' 0.55 0.43 ... 0.3285 0.1465 0.24]
 ['F' 0.63 0.49 ... 0.458 0.2765 0.32]
 ['I' 0.16 0.11 ... 0.0055 0.003 0.005]
 ...
 ['I' 0.435 0.33 ... 0.151 0.0785 0.0815]
 ['I' 0.345 0.27 ... 0.098 0.049 0.07]
 ['I' 0.425 0.325 ... 0.1525 0.0785 0.105]]


In [78]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
X[:,0]=le.fit_transform(X[:,0])

In [79]:
print(X)

[[0 0.55 0.43 ... 0.3285 0.1465 0.24]
 [0 0.63 0.49 ... 0.458 0.2765 0.32]
 [1 0.16 0.11 ... 0.0055 0.003 0.005]
 ...
 [1 0.435 0.33 ... 0.151 0.0785 0.0815]
 [1 0.345 0.27 ... 0.098 0.049 0.07]
 [1 0.425 0.325 ... 0.1525 0.0785 0.105]]


### Splitting the dataset into the Training set and Test set

In [103]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [104]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test=sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [105]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [106]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [107]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [108]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [86]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [87]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 34.5703
Epoch 2/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 4.1044
Epoch 3/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.8401
Epoch 4/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.9174
Epoch 5/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.7948
Epoch 6/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.8029
Epoch 7/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.7698
Epoch 8/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - loss: 3.7524
Epoch 9/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 3.7372
Epoch 10/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 3.7446
Epoch 11/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 5s 1ms/step - loss: 3.7306
Epoch 12/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.7370
Epoch 13/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.7307
Epoch 14/100
2266/2266 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 3.6688
Epoch 15/100
2

In [88]:
y_pred=(ann.predict(sc.transform(X_test))).flatten()

567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


In [89]:
y_pred.shape

(18123,)

In [90]:
y_test.shape

(18123,)

In [101]:
y_test

array([ 6,  7,  9, ..., 10,  8,  9])

In [102]:
y_pred

array([ 1.4889696,  1.231805 ,  2.8309314, ..., 25.834024 ,  1.3774911,
        4.868935 ], dtype=float32)

In [91]:
# from sklearn.metrics import mean_squared_log_error
# def rmsle(y_test,y_preds):
#     return np.sqrt(mean_squared_log_error(y_test,y_preds))

In [98]:
def rmsle(y_true, y_pred):
    # Logarithm of predictions and true values, adding 1 to avoid taking the log of zero
    log_pred = np.log1p(y_pred)
    log_true = np.log1p(y_true)
    
    # Squared differences between logarithms
    squared_diff = (log_pred - log_true) ** 2
    
    # Mean squared difference
    mean_squared_diff = np.mean(squared_diff)
    
    # Root mean squared difference
    rmsle = np.sqrt(mean_squared_diff)
    
    return rmsle


In [99]:
rmsle_value=rmsle(y_test,y_pred)

In [100]:
rmsle_value

0.7999576342421163

### Predicting the results of the Test set

In [94]:
mse = ann.evaluate(X_test, y_test)
print("Mean Squared Error on Test Data:", mse)

567/567 ━━━━━━━━━━━━━━━━━━━━ 1s 933us/step - loss: 3.5571
Mean Squared Error on Test Data: 3.5345535278320312


In [95]:
rmse = np.sqrt(mse)
print("Root Mean Squared Error on Test Data:", rmse)


Root Mean Squared Error on Test Data: 1.8800408314268153
